name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - master
      - feature/*

pr:
  branches:
    include:
      - master

jobs:
  - job: BuildAndRunUnitTests
    displayName: Build and run unit tests

    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - task: Maven@3
        displayName: Build with Maven
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: false
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          sonarQubeRunAnalysis: false
          sqMavenPluginVersionChoice: 'latest'

      - task: CopyFiles@2
        displayName: Copy files to artifacts
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/target/azure-functions/sparetimedevs-win/'
          targetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: DeleteFiles@1
        displayName: Remove local.settings.json from artifacts
        inputs:
          sourceFolder: '$(Build.ArtifactStagingDirectory)'
          contents: 'local.settings.json'

      - task: PublishBuildArtifacts@1
        displayName: Publish artifacts
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'drop'

  - job: RunFunctionalTests
    displayName: Run functional tests

    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'

      - task: DockerCompose@0
        displayName: Run services
        inputs:
          action: Run services
          workingDirectory: $(Build.SourcesDirectory)
          dockerComposeFile: ./mongodb/docker-compose.yml

      - script: sudo npm i -g azure-functions-core-tools --unsafe-perm true
        displayName: Install Azure Functions Core tools

      - script: sudo npm i -g newman
        displayName: Install Newman CLI

      - script: mvn clean install -DskipTests
        displayName: Maven clean install without running tests

      - script: mvn azure-functions:package
        displayName: Package AZ Function App

      - script: mvn azure-functions:run &
        displayName: Run AZ Function App

      - script: newman run src/test/functional/win-function-app-newman-tests.json
        displayName: Run Newman CLI tests