name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  - repo: self

queue:
  name: Hosted macOS
  demands: java

trigger:
  batch: true
  branches:
    include:
      - master
      - feature/*
pr:
  branches:
    include:
      - master

steps:
  - script: npm i -g azure-functions-core-tools --unsafe-perm true
    displayName: 'Install Azure Functions Core tools'

  - task: Maven@3
    displayName: 'Build with Maven'
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: false
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      sonarQubeRunAnalysis: false
      sqMavenPluginVersionChoice: 'latest'

  # - task: DockerInstaller@0
  #   inputs:
  #     dockerVersion: '17.09.0-ce'

  # - task: DockerCompose@0
  #   inputs:
  #     containerregistrytype: 'Container Registry'
  #     dockerComposeFile: '$(Build.SourcesDirectory)/mongodb/docker-compose.yml'
  #     action: 'Run a Docker Compose command'

  # - task: DockerCompose@0
  #   inputs:
  #     containerregistrytype: 'Azure Container Registry'
  #     dockerComposeFile: '**/**/docker-compose.yml'
  #     action: 'Run a Docker Compose command'

  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'

  - task: DockerCompose@0
    displayName: Run services
    inputs:
      action: Run services
      workingDirectory: $(Build.SourcesDirectory)
      # azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      # azureContainerRegistry: $(azureContainerRegistry)
      dockerComposeFile: ./mongodb/docker-compose.yml
      projectName: $(Build.Repository.Name)
      # qualifyImageNames: true
      # buildImages: true
      abortOnContainerExit: true
      detached: false

  # - script: docker-compose -f ./mongodb/docker-compose.yml up -d
  #   displayName: 'Compose up MongoDB docker container'
  #   workingDirectory: '$(System.DefaultWorkingDirectory)'

  - script: npm i -g newman
    displayName: 'Install Newman CLI'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: CopyFiles@2
    displayName: 'Copy files to artifacts'
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/target/azure-functions/sparetimedevs-win/'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: DeleteFiles@1
    displayName: 'Remove local.settings.json from artifacts'
    inputs:
      sourceFolder: '$(Build.ArtifactStagingDirectory)'
      contents: 'local.settings.json'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage'
    inputs:
      codeCoverageTool: 'jaCoCo'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/target/site/jacoco'
      additionalCodeCoverageFiles: '$(System.DefaultWorkingDirectory)/target/jacoco.exec'
