version: '3.7'

services:

  mongodb:
    image: mongo:4.2.1-windowsservercore-ltsc2016
    container_name: win-mongo
#    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sparetimedev
      MONGO_INITDB_ROOT_PASSWORD: APjGgfK6GIbkmv6XCZ
#    volumes:
#      - mongodb_data:/data/db
#      - mongodb_data_config:/data/configdb
    ports:
      - 23018:27017
    command: mongod

#volumes:
#  mongodb_data:
#  mongodb_data_config: