version: '3.7'

services:

  mongodb:
    image: mongo:4.1.3
    container_name: win-mongo
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_ROOT_USERNAME: sparetimedev
      MONGO_INITDB_ROOT_PASSWORD: APjGgfK6GIbkmv6XCZ
    volumes:
      - ./data/db:/data/db
    ports:
      - 23018:27017
    command: mongod --logpath=/dev/null